"""Write a season with one Firestore client and read it back with a SECOND one.

**Why the second client is the whole test.** Reading back through the object that just
wrote is satisfied by a dictionary, which is exactly what this project had before: a
Season Ledger whose clocks were computed and then dropped at the end of the request. The
claim being made is that the record survives the process, so the check has to leave the
process's memory behind. The ledger's own docstring said this from the day it was
written and nothing had ever done it.

CI cannot run this: no credentials, and a test that wrote to the real seasons collection
would be editing a legal record. So this writes `docs/SEASON.md` and the default suite
reads that, the same split as the deployment probe and the Gemma run.
"""

from __future__ import annotations

import os
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "agents" / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "core" / "src"))

from curtail_agents.ledger import record_order
from curtail_agents.season_store import (
    COLLECTION,
    FirestoreSeasonStore,
    SeasonStoreUnavailableError,
    season_payload,
)
from curtail_core.basins import Basin
from curtail_core.clocks import SignatoryRole

REPO = Path(__file__).resolve().parents[1]
RECORD = REPO / "docs" / "SEASON.md"

#: A probe basin, so a demonstration never writes into a real basin's season.
PROBE_BASIN = Basin.SCOTT
ADOPTED = datetime(2026, 6, 10, 17, 0, tzinfo=UTC)
ORDER_ID = "PROBE-SCOTT-2026-06-10"


def main() -> int:
    project = os.environ.get("GOOGLE_CLOUD_PROJECT") or "curtail-505118"

    try:
        writer = FirestoreSeasonStore(project)
    except SeasonStoreUnavailableError as exc:
        print(f"no durable store to probe: {exc}", file=sys.stderr)
        return 1

    entry = record_order(
        ADOPTED,
        order_id=ORDER_ID,
        order_type="curtailment_order",
        signatory=SignatoryRole.DEPUTY_DIRECTOR,
        certification_days=7,
        information_response_days=5,
    )

    started = datetime.now(UTC)
    try:
        existing = writer.load(PROBE_BASIN)
        if any(e.order_id == ORDER_ID for e in existing.entries):
            print(f"{ORDER_ID} is already on record; the ledger is append-only, reusing it")
            pass
        else:
            writer.append_entry(PROBE_BASIN, entry)
    except SeasonStoreUnavailableError as exc:
        print(f"the write failed, so nothing is recorded: {exc}", file=sys.stderr)
        return 1

    # The second client. Built independently, sharing no state with the writer.
    reader = FirestoreSeasonStore(project)
    observed = datetime(2026, 6, 20, 12, 0, tzinfo=UTC)
    payload = season_payload(reader, PROBE_BASIN, now=observed)

    ids = [o["order_id"] for o in payload["orders"]]
    if ORDER_ID not in ids:
        print(
            f"the second client did not see {ORDER_ID}. Nothing is durable and nothing "
            "is recorded.",
            file=sys.stderr,
        )
        return 1

    clocks = "\n".join(
        f"| `{c['clock']}` | {c['opens_at'][:10]} | {c['closes_at'][:10]} | "
        f"{'**yes**' if c['exhaustion_required'] else 'no'} |"
        for c in payload["open_clocks"]
    )

    RECORD.write_text(
        f"""# The season survives the process

Generated by `scripts/probe_season_store.py`. Do not hand-edit: a hand-written line
inside a generated file is the one line nothing checks.

The Fleet track asks for a system that maintains context across weeks of asynchronous
operations. This is the evidence, and the shape of the check is the point.

- Store: **Cloud Firestore**, native mode, project `{project}`, collection `{COLLECTION}`
- Written by one client at `{started.isoformat()}`
- **Read back by a SECOND, independently constructed client**, sharing no memory with
  the writer. Reading through the object that just wrote is satisfied by a dictionary,
  which is exactly what this project had before.
- Orders on record for the probe basin: {", ".join(f"`{i}`" for i in ids)}
- Durable: **{payload["durable"]}**

## Statutory clocks the second client read back

Adopted `{ADOPTED.date().isoformat()}`, observed as of `{observed.date().isoformat()}`.

| Clock | Opens | Closes | Exhaustion required |
|---|---|---|---|
{clocks}

`reconsideration_petition` carries **exhaustion required**, and that is not a detail.
These orders issue under delegated authority, so a petition for reconsideration under
Water Code 1122 is a mandatory prerequisite to judicial review rather than an optional
first step. A watermaster who lets that window close has not lost a month, they have
foreclosed the challenge.

The 90-day Board response window is in **1122, not 1123**, which is a citation this
project has had to correct once already.

## What this record does not prove

That the deployed service is using this store right now. Nothing here re-probes on its
own and CI never queries the network, so this describes the moment above. `GET
/api/season/{{basin}}` reports `durable` and names its store on every response, which is
where a reader should look for the live answer.
""",
        encoding="utf-8",
    )
    print(
        f"wrote {RECORD.relative_to(REPO)}: {len(ids)} order(s) read back by a second "
        f"client, {len(payload['open_clocks'])} clock(s) open"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
