"""Record what the chaos drill actually proved, so the video can quote it.

**The strongest finding this project has lived only in terminal output.** `FACTS.md` says
`make chaos` "screens the same injection alone and embedded in an order and reports both
verdicts", and it records NEITHER verdict. The result scrolls away, and the demo video is
about to narrate it. Every figure spoken on camera is supposed to come from a committed,
guarded source, because a published video cannot be corrected.

Split the same way as the deployment probe, for the same reason: this half needs the
network and a project, the TEST that reads the record needs neither, so CI never depends
on Model Armor being reachable.

**It refuses to write a record of a partial drill.** A record exists to be quoted, and a
half-demonstrated run quoted as a full one is precisely the false green the drill was
built to disprove.

**Do not call this directly to record.** `make chaos-recording` is the documented entry
point, and it calls this with `--print` so one run is both the on-camera drill and the
record. They were two near-identically named targets until a review pointed out that the
one everybody runs never touched the record, which let the record go stale while the gate
passed on it.

    GOOGLE_CLOUD_PROJECT=curtail-505118 make chaos-recording          # drill + record
    GOOGLE_CLOUD_PROJECT=curtail-505118 uv run python scripts/record_chaos.py --check
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "CHAOS.md"

#: Everything below this heading is volatile by design (timestamps, project id).
STABLE_END = "## When this was recorded"


def build(*, show: bool = False) -> str:
    sys.path.insert(0, str(REPO / "agents" / "src"))
    from curtail_agents.chaos import run_drill

    project = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
    if not project:
        raise SystemExit(
            "GOOGLE_CLOUD_PROJECT is not set. Without it the poisoned-document scenario "
            "cannot reach Model Armor, and a record of a partial drill is worse than no "
            "record: it reads identically to a complete one."
        )

    results = run_drill()

    # **Printed, because this is also the on-camera run.** `make chaos-recording` calls
    # this, and a reviewer pointed out that the recorder and the documented drill command
    # had drifted into two near-identically named targets: the one everybody runs printed
    # the drill and never touched the record, so the record could sit stale while the gate
    # passed on it. One run, printed and recorded, removes the gap rather than documenting
    # around it.
    if show:
        print("CURTAIL chaos drill: three injected failures, three guards\n")
        for result in results:
            print(result.render())
            print()

    partial = [r for r in results if not r.complete]
    if partial:
        raise SystemExit(
            "REFUSING to write the record. These scenarios did not demonstrate their "
            "guard in full: " + ", ".join(f"{r.name} ({'; '.join(r.unexercised)})" for r in partial)
        )

    lines: list[str] = [
        "# What the chaos drill proved",
        "",
        "**Generated by `scripts/record_chaos.py` from a real run. Do not hand-edit.**",
        "",
        "This exists because the drill's strongest evidence used to live only in terminal",
        "output. The demo video narrates it, and a published video cannot be corrected, so",
        "the numbers spoken on camera come from here.",
        "",
        "The rubric for this track asks one question by name: **how does the system recover",
        "if a worker agent loops or returns a hallucination?** These are the answers, run",
        "live rather than described.",
        "",
        f"{len(results)} of {len(results)} scenarios demonstrated their guard in full.",
        "",
    ]

    for result in results:
        lines.append(f"## {result.name}")
        lines.append("")
        lines.append(f"- **Injected:** {result.injected}")
        lines.append(f"- **Guard:** {result.guard}")
        lines.append("- **Verdict:** PASS, with nothing it names left unexercised.")
        lines.append("")
        lines.extend(f"- {line}" for line in result.evidence)
        lines.append("")

    lines += [
        STABLE_END,
        "",
        f"- Project the drill called: `{project}`",
        f"- Recorded at: `{datetime.now(UTC).isoformat(timespec='seconds')}`",
        "",
        "Re-run before recording. A drill is evidence about the moment it ran, and this",
        "one calls a live vendor filter whose behaviour is not ours to pin.",
        "",
    ]
    return "\n".join(lines)


def _stable(text: str) -> str:
    """The part that must not drift, which excludes the stamp."""
    return text.split(STABLE_END)[0]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the record has drifted")
    parser.add_argument(
        "--print",
        dest="show",
        action="store_true",
        help="also print the drill to stdout, which is what gets recorded on camera",
    )
    args = parser.parse_args(argv)

    fresh = build(show=args.show)
    if not args.check:
        OUT.write_text(fresh)
        print(f"wrote {OUT.relative_to(REPO)}")
        return 0

    if not OUT.exists():
        print(f"{OUT.relative_to(REPO)} does not exist. Run without --check.", file=sys.stderr)
        return 1
    if _stable(OUT.read_text()) != _stable(fresh):
        print(f"{OUT.relative_to(REPO)} disagrees with a fresh drill run.", file=sys.stderr)
        return 1
    print(f"{OUT.relative_to(REPO)} matches a fresh drill run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
