"""Run Gemma over a real Board order, on this machine, and record what it produced.

**Why this is a script and not a test.** CI has no GPU, no Ollama and no corpus, and the
corpus PDFs are gitignored government documents that cannot live in the repository. A
test that skipped when the model was absent would be a false green, and one that mocked
the model and called the result evidence would be worse. So the work splits: this writes
`docs/NORMALIZER.md` from a real run, and `test_the_local_run_record_is_honest` in the
default suite reads that record and fails if it is vacuous, unpinned or overclaiming.

The same shape as `probe_deployment.py`, for the same reason.
"""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "agents" / "src"))

from curtail_agents.normalizer import (
    NormalizerUnavailableError,
    normalize,
    split_narrative,
)

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "data" / "corpus" / "addendum6-shasta-attach-a.pdf"
RECORD = REPO / "docs" / "NORMALIZER.md"


def _text_of(pdf: Path) -> str:
    if shutil.which("pdftotext") is None:
        raise SystemExit("pdftotext is not installed, so the source cannot be read")
    result = subprocess.run(
        ["pdftotext", "-layout", str(pdf), "-"],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(f"pdftotext failed on {pdf.name}: {result.stderr[:300]}")
    return result.stdout


def main() -> int:
    if not SOURCE.exists():
        print(
            f"the source document is absent: {SOURCE}. The corpus is gitignored, so "
            "this runs only where it has been fetched.",
            file=sys.stderr,
        )
        return 1

    raw = _text_of(SOURCE)
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    narrative, attachment = split_narrative(raw)

    started = datetime.now(UTC)
    try:
        result = normalize(narrative)
    except NormalizerUnavailableError as exc:
        print(f"the local model was unreachable, so nothing was recorded: {exc}", file=sys.stderr)
        return 1
    elapsed = (datetime.now(UTC) - started).total_seconds()

    verified = "\n".join(f"| `{k}` | {v} |" for k, v in sorted(result.values.items()))
    notes = "\n".join(f"- {n}" for n in result.notes) or "- none"

    RECORD.write_text(
        f"""# What the local Gemma actually read

Generated by `scripts/run_normalizer.py`. Do not hand-edit: a hand-written line inside a
generated file is the one line nothing checks.

This exists because CI cannot run this model. There is no GPU on a runner, the runtime
is not installed there, and the source PDFs are gitignored government documents. So the
real run happens here and leaves a record, and the default test suite reads the record
rather than pretending to verify the model itself.

- Model: `{result.model}`, run locally through Ollama. **No document left this machine.**
- Source: `{SOURCE.name}`, sha256 `{digest}`
- Read at: `{started.isoformat()}`
- Wall clock: {elapsed:.1f}s
- Document: {len(raw)} characters, of which {len(narrative)} is the narrative this model
  read and {len(attachment)} is the Attachment A table, which is routed to the
  deterministic parser instead.

## Verified, each found verbatim in the source

| Field | Value |
|---|---|
{verified}

## Proposed, and never treated as a value

- `proposed_action`: **{result.proposed_action or "none"}**

The action is the model's READING of what the order does, not a value quoted from it.
It is kept apart from the verified fields because a substring test cannot separate a
quotation from an interpretation: the word "curtail" appears in any document containing
"curtailments", including this one, whose actual act is reinstatement.

## Not answered

- Declined by the model: {", ".join(f"`{f}`" for f in result.absent) or "none"}
- Rejected by the guard: {", ".join(f"`{f}`" for f in result.unverified) or "none"}

## Notes carried into the audit record

{notes}

## What this model is NOT allowed to do

It does not read law out of the document. `priority_cutoff` was removed from the schema
after two runs disagreed: this addendum states a RANGE, "priority dates between and
including November 25, 1912 and December 31, 1957", and both endpoints are in the text,
so both pass a verbatim check while only one is legally operative. Choosing between them
is the determination 23 CCR 875(b) vests in the Deputy Director.

Gemma identifies and files the document. The deterministic parsers read its table. A
human reads its law.
""",
        encoding="utf-8",
    )
    print(
        f"wrote {RECORD.relative_to(REPO)}: {len(result.values)} verified, "
        f"{len(result.unverified)} rejected, action {result.proposed_action!r}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
