"""Verify that every backtest quote actually appears in the document it names.

This closes the last finding of the adversarial review, which was raised as
UNCERTAIN and turned out to be real: nothing linked a backtest case to the
document it claims to quote. A human typed a reading and a sentence, and the
engine scored against them. That is precisely the mechanism which let the
retired 39.3 cfs reading, which appears nowhere in Shasta Addendum 6, propagate
out of a research summary into five artifacts and survive both a verification
pass and a green test suite.

The check has to survive a constraint: `data/corpus/` is gitignored, because a
repository is not a document archive, so CI cannot open the PDFs. A test that
skipped when the corpus was absent would be a false green, and this project has
already been bitten by exactly that.

So the shape is the same as `docs/FACTS.md`. This script runs where the corpus
exists and writes `data/quote_verification.json`, recording per case whether the
quote was found, together with the SHA256 of the document it was found in. CI
then checks that record is complete, internally consistent, and covers every
case. Neither half is sufficient alone: the record proves a human ran the check
against real bytes, and the CI test proves nobody quietly dropped a case from it.

Run:  uv run python scripts/verify_backtest_quotes.py
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "core" / "src"))

CASES = REPO / "data" / "backtest_cases.json"
CORPUS = REPO / "data" / "corpus"
OUT = REPO / "data" / "quote_verification.json"


def _normalise(text: str) -> str:
    """Collapse whitespace so a quote spanning a line break still matches.

    `pdftotext -layout` preserves column padding, so a sentence in the PDF is
    full of runs of spaces and newlines that a quote typed on one line does not
    have. Comparing raw would fail on every case for a reason that has nothing to
    do with whether the sentence is really there.
    """
    return re.sub(r"\s+", " ", text).strip()


def _pdf_for(case_id: str) -> Path:
    """`scott_2024/addenda/7` maps to `scott_2024__addenda__7.pdf`."""
    return CORPUS / f"{case_id.replace('/', '__')}.pdf"


def _text_of(path: Path) -> str:
    proc = subprocess.run(
        ["pdftotext", "-layout", str(path), "-"],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"pdftotext failed on {path.name}: {proc.stderr[:160]}")
    return proc.stdout


def verify() -> dict[str, Any]:
    data = json.loads(CASES.read_text())
    records: dict[str, Any] = {}
    failures: list[str] = []

    for case in data["cases"]:
        case_id = case["id"]
        quote = _normalise(case["source_quote"])
        pdf = _pdf_for(case_id)

        if not pdf.exists():
            records[case_id] = {"verified": False, "reason": "pdf not on disk"}
            failures.append(f"{case_id}: PDF not fetched, cannot verify")
            continue

        digest = hashlib.sha256(pdf.read_bytes()).hexdigest()

        if case.get("read_method") == "vision":
            # A scan has no text layer, so the quote cannot be grepped. It was
            # transcribed from the rendered page by a person. Record that
            # honestly rather than reporting a verification that did not happen.
            records[case_id] = {
                "verified": False,
                "reason": (
                    "read from rendered pages; no text layer exists to grep. The "
                    "quote was transcribed by a human and cannot be machine "
                    "checked without re-rendering."
                ),
                "sha256": digest,
                "read_method": "vision",
            }
            continue

        haystack = _normalise(_text_of(pdf))
        found = quote in haystack
        records[case_id] = {
            "verified": found,
            "sha256": digest,
            "read_method": "text_layer",
            "reading_cfs": case["reading_cfs"],
            "reading_in_quote": f"{case['reading_cfs']:g}" in case["source_quote"],
        }
        if not found:
            failures.append(f"{case_id}: quote NOT found in the document it names")

    return {
        "$note": [
            "Generated by scripts/verify_backtest_quotes.py. Do not hand edit.",
            "",
            "Each entry records whether a backtest case's source_quote was found",
            "verbatim in the document that case names, plus the SHA256 of the",
            "bytes it was checked against. Vision-read cases are recorded as",
            "unverifiable rather than verified, because a scan has no text layer",
            "to grep and the quote was transcribed by a person.",
            "",
            "data/corpus is gitignored, so CI cannot repeat this. CI instead",
            "checks that this record covers every case and contains no failure.",
        ],
        "cases": records,
        "summary": {
            "total": len(data["cases"]),
            "verified": sum(1 for r in records.values() if r.get("verified")),
            "vision_unverifiable": sum(
                1 for r in records.values() if r.get("read_method") == "vision"
            ),
            "failed": len(failures),
        },
        "failures": failures,
    }


def main() -> int:
    result = verify()
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")

    s = result["summary"]
    print(f"cases                 {s['total']}")
    print(f"  quote verified      {s['verified']}")
    print(f"  vision, unverifiable {s['vision_unverifiable']}")
    print(f"  FAILED              {s['failed']}")
    print(f"\nwrote {OUT.relative_to(REPO)}")

    for line in result["failures"]:
        print(f"  FAIL {line}")

    if result["failures"]:
        print(
            "\nA quote that does not appear in the document it names is the exact "
            "shape of the retired 39.3 incident. Fix the case or remove it. Never "
            "adjust the quote to make a number fit."
        )
    return 1 if result["failures"] else 0


if __name__ == "__main__":
    sys.exit(main())
